name: Run tests on each push

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened]

jobs:
  test_ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Golang environment
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.21"
      - name: Run tests
        run: go test ./... -v
