name: Run tests on each push

on: [push]

jobs:
  test_ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Golang environment
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18"
      - name: Run tests
        run: go test ./... -v
